[package]
name = "ivm-compile"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ivm-common = { path = "../ivm-common" }
constant_pool_macro = { git = "https://github.com/Redempt/constant_pool" }
