[package]
name = "sus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ivm-vm = { path = "../../ivm-vm" }
ivm-compile = { path = "../../ivm-compile" }