[package]
name = "ivm-fe"
version = "0.1.0"
edition = "2021"
description = "A front-end implementation of ivmc."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
