[package]
name = "ivm-vm"
version = "0.1.0"
edition = "2021"
description = "The virtual machine for ivm bytecode."
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ivm-compile = { path = "../ivm-compile" }
